"""Compatibility facade for sectioned combat rules.

New combat implementation belongs under `tools/diysim/combat/`. This module
re-exports the public Phase-2 primitives so existing imports remain stable while
the simulator is reorganized section-by-section.
"""

from .combat import (
    AFFINITY_DAMAGE_MULTIPLIERS,
    BASIC_ATTACK,
    BLEED_ESCALATED_RATE,
    BLEED_INITIAL_RATE,
    BURN_RATE,
    FREEZE_MAX_AFFECTED_ROUNDS,
    LINKED_STATUS,
    STAGGERED_ROUNDS,
    STUN_LOSS_CHANCE,
    ActionKind,
    ActiveStatus,
    Affinity,
    CombatAction,
    CombatUnit,
    Combatant,
    DamageKind,
    Element,
    Rank,
    Side,
    StatusName,
    StatusRider,
    TargetScope,
    TargetSide,
    affinity_damage_multiplier,
    apply_status,
    effective_attack,
    effective_defense,
    effective_magic,
    effective_speed,
    effective_spirit,
    element_affinity,
    healing_amount,
    linked_status_affinity_modifier,
    resolve_mp_cost,
    status_application_chance,
)

__all__ = [
    "AFFINITY_DAMAGE_MULTIPLIERS",
    "ActionKind",
    "ActiveStatus",
    "Affinity",
    "BASIC_ATTACK",
    "BLEED_ESCALATED_RATE",
    "BLEED_INITIAL_RATE",
    "BURN_RATE",
    "CombatAction",
    "CombatUnit",
    "Combatant",
    "DamageKind",
    "Element",
    "FREEZE_MAX_AFFECTED_ROUNDS",
    "LINKED_STATUS",
    "Rank",
    "STAGGERED_ROUNDS",
    "STUN_LOSS_CHANCE",
    "Side",
    "StatusName",
    "StatusRider",
    "TargetScope",
    "TargetSide",
    "affinity_damage_multiplier",
    "apply_status",
    "effective_attack",
    "effective_defense",
    "effective_magic",
    "effective_speed",
    "effective_spirit",
    "element_affinity",
    "healing_amount",
    "linked_status_affinity_modifier",
    "resolve_mp_cost",
    "status_application_chance",
]
