"""Sectioned combat primitives for the Diyse balance simulator."""

from .advanced_runtime import (
    AdvancedBattleOutcome,
    AdvancedBattleScenario,
    AdvancedSimulationSummary,
    run_advanced_battle,
    simulate_advanced,
)
from .criticals import BASE_CRIT_CHANCE, CRIT_CHANCE_CAP, CRIT_MULTIPLIER
from .damage import PENETRATION_CAP, direct_damage, magical_damage, physical_damage
from .derived_stats import (
    effective_attack,
    effective_defense,
    effective_magic,
    effective_speed,
    effective_spirit,
)
from .elements import (
    AFFINITY_DAMAGE_MULTIPLIERS,
    LINKED_STATUS,
    affinity_damage_multiplier,
    element_affinity,
    linked_status_affinity_modifier,
)
from .healing import healing_amount
from .hit_evasion import MAX_HIT_CHANCE, MIN_HIT_CHANCE, adjusted_hit_chance
from .models import (
    BASIC_ATTACK,
    ActionKind,
    ActiveStatus,
    Affinity,
    CombatAction,
    CombatUnit,
    Combatant,
    DamageKind,
    Element,
    Rank,
    Side,
    StatusName,
    StatusRider,
    TargetScope,
    TargetSide,
)
from .mp import resolve_mp_cost
from .simple_runtime import (
    ActionProfile,
    BattleOutcome,
    BattleScenario,
    CombatantTemplate,
    SimulationSummary,
    run_battle,
    simulate,
)
from .statuses import (
    BLEED_ESCALATED_RATE,
    BLEED_INITIAL_RATE,
    BURN_RATE,
    FREEZE_MAX_AFFECTED_ROUNDS,
    STAGGERED_ROUNDS,
    STUN_LOSS_CHANCE,
    apply_status,
    status_application_chance,
)

__all__ = [
    "AFFINITY_DAMAGE_MULTIPLIERS",
    "ActionKind",
    "ActionProfile",
    "ActiveStatus",
    "AdvancedBattleOutcome",
    "AdvancedBattleScenario",
    "AdvancedSimulationSummary",
    "Affinity",
    "BASE_CRIT_CHANCE",
    "BASIC_ATTACK",
    "BLEED_ESCALATED_RATE",
    "BLEED_INITIAL_RATE",
    "BURN_RATE",
    "BattleOutcome",
    "BattleScenario",
    "CRIT_CHANCE_CAP",
    "CRIT_MULTIPLIER",
    "CombatAction",
    "CombatUnit",
    "Combatant",
    "CombatantTemplate",
    "DamageKind",
    "Element",
    "FREEZE_MAX_AFFECTED_ROUNDS",
    "LINKED_STATUS",
    "MAX_HIT_CHANCE",
    "MIN_HIT_CHANCE",
    "PENETRATION_CAP",
    "Rank",
    "STAGGERED_ROUNDS",
    "STUN_LOSS_CHANCE",
    "Side",
    "SimulationSummary",
    "StatusName",
    "StatusRider",
    "TargetScope",
    "TargetSide",
    "adjusted_hit_chance",
    "affinity_damage_multiplier",
    "apply_status",
    "direct_damage",
    "effective_attack",
    "effective_defense",
    "effective_magic",
    "effective_speed",
    "effective_spirit",
    "element_affinity",
    "healing_amount",
    "linked_status_affinity_modifier",
    "magical_damage",
    "physical_damage",
    "resolve_mp_cost",
    "run_advanced_battle",
    "run_battle",
    "simulate",
    "simulate_advanced",
    "status_application_chance",
]
